- alias: Acknowledge the KL43 door alert
  trigger: 
    platform: event
    event_type: telegram_callback
    event_data: 
      data: /kl43_door_acknowledge
  action:
  - service: homeassistant.turn_off
    data:  
      entity_id: alert.kl43_door

- alias: Acknowledge the KL43 motion alert
  trigger: 
    platform: event
    event_type: telegram_callback
    event_data: 
      data: /kl43_motion_acknowledge
  action:
  - service: homeassistant.turn_off
    data:  
      entity_id: alert.kl43_motion

- alias: Acknowledge the KL43 humidity alert
  trigger: 
    platform: event
    event_type: telegram_callback
    event_data: 
      data: /kl43_humidity_acknowledge
  action:
  - service: homeassistant.turn_off
    data:  
      entity_id: alert.kl43_humidity

## Availability
- alias: Daily report with unavailable entities
  initial_state: 'true'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: template
    value_template: >
              {% set unavails = states.sensor | selectattr('state', 'eq', 'unavailable')
                               | map(attribute='name')
                               | list
                               | length  %}
               {{ unavails > 0 }}
  action:
    - service: notify.olivia
      data_template:
        message: >
          {%- for item in states if item.state is defined and item.state == 'unavailable' -%}
            "{{ item.name | replace('_', ' ') }} is unavailable"
          {%- endfor -%}
    - service: notify.heziwm
      data_template:
        message: >
          {%- for item in states if item.state is defined and item.state == 'unavailable' -%}
            "{{ item.name | replace('_', ' ') }} is unavailable"
          {%- endfor -%}

- alias: Daily report with unknown state entities
  initial_state: 'true'
  trigger:
    platform: time
    at: '20:10:00'
  condition:
    condition: template
    value_template: >
              {% set unavails = states.sensor | selectattr('state', 'eq', 'unknown')
                               | map(attribute='name')
                               | list
                               | length  %}
               {{ unavails > 0 }}
  action:
    - service: notify.olivia
      data_template:
        message: >
          {%- for item in states if item.state is defined and item.state == 'unknown' -%}
            "{{ item.name | replace('_', ' ') }} is in unknown state"
          {%- endfor -%}
    - service: notify.heziwm
      data_template:
        message: >
          {%- for item in states if item.state is defined and item.state == 'unknown' -%}
            "{{ item.name | replace('_', ' ') }} is in unknown state"
          {%- endfor -%}
## Light
- alias: Lights On
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.ble_opening_xiaomi_sensor_door_status
      to: 'on'
  action:
    service: light.turn_on
    entity_id: group.lights

- alias: Lights Off
  initial_state: 'true'
  trigger:
    - platform: state
      entity_id: binary_sensor.ble_opening_xiaomi_sensor_door_status
      to: 'off'
  action:
    service: light.turn_off
    entity_id: group.lights
