homeassistant:

config:

automation: !include automations.yaml
group: !include groups.yaml
alert: !include_dir_merge_named alerts

http:
  ssl_certificate: !secret sslpem
  ssl_key: !secret sslkey

websocket_api:

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token

ble_monitor:
  discovery: False
  devices:
    - mac: 'A4:C1:38:D4:AB:CB'
      encryption_key: !secret xiaomi_sensor_door_ek
      temperature_unit: C
      name: 'Xiaomi_Sensor_Door'
    - mac: 'A4:C1:38:F3:0E:16'
      encryption_key: !secret xiaomi_sensor_countertop1_ek
      temperature_unit: C
      name: 'Xiaomi_Sensor_Countertop1'
    - mac: 'A4:C1:38:BA:D6:90'
      encryption_key: !secret xiaomi_sensor_countertop2_ek
      temperature_unit: C                  
      name: 'Xiaomi_Sensor_Countertop2'
    - mac: 'A4:C1:38:81:2F:E0'
      encryption_key: !secret xiaomi_sensor_storageRack2_top_ek
      temperature_unit: C
      name: 'Xiaomi_Sensor_StorageRack2_Top'
    - mac: 'A4:C1:38:A4:F5:48'
      encryption_key: !secret xiaomi_sensor_storageRack2_bottom_ek
      temperature_unit: C
      name: 'Xiaomi_Sensor_StorageRack2_Bottom'
    - mac: 'A4:C1:38:06:50:32'
      encryption_key: !secret xiaomi_sensor_storageRack1_bottom_ek
      temperature_unit: C      
      name: 'Xiaomi_Sensor_StorageRack1_Bottom'
    - mac: 'A4:C1:38:F3:27:EB'
      encryption_key: !secret xiaomi_sensor_storageRack1_mid_ek
      temperature_unit: C   
      name: 'Xiaomi_Sensor_StorageRack1_Mid'
    - mac: 'A4:C1:38:46:20:CF'
      encryption_key: !secret xiaomi_sensor_storageRack1_top_ek
      temperature_unit: C
      name: 'Xiaomi_Sensor_StorageRack1_Top' 
    - mac: 'E4:AA:EC:34:E1:66'
      encryption_key: !secret xiaomi_sensor_door_status_ek
      name: 'Xiaomi_Sensor_Door_Status' 

sensor:
  - platform: websocket_api
  - platform: version
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_15m
      - type: processor_temperature

binary_sensor:
  - platform: template
    sensors:
      pi_cpu_too_hot:
        value_template: "{{ states('sensor.processor_temperature') | int > 40 }}"
        friendly_name: 'PI CPU too hot'
  - platform: template
    sensors:
      pi_cpu_load_high:
        value_template: "{{ states('sensor.load_15m') | int > 1 }}"
        friendly_name: 'PI CPU load too high'
  - platform: template
    sensors:
      pi_memory_low:
        value_template: "{{ states('sensor.memory_use_percent') | int > 90 }}"
        friendly_name: 'PI memory low'
  - platform: template
    sensors:
      pi_root_low_space:
        value_template: "{{ states('sensor.disk_use_percent') | int > 90 }}"
        friendly_name: 'PI root low space'

lovelace:
  mode: yaml

recorder:
  purge_keep_days: 365
  include:
    entities:
      - sensor.ble_humidity_xiaomi_sensor_countertop1
      - sensor.ble_humidity_xiaomi_sensor_countertop2
      - sensor.ble_humidity_xiaomi_sensor_door
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_bottom
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_mid
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_top
      - sensor.ble_humidity_xiaomi_sensor_storagerack2_bottom
      - sensor.ble_humidity_xiaomi_sensor_storagerack2_top
      - sensor.ble_temperature_xiaomi_sensor_countertop1
      - sensor.ble_temperature_xiaomi_sensor_countertop2
      - sensor.ble_temperature_xiaomi_sensor_door
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_bottom
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_mid
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_top
      - sensor.ble_temperature_xiaomi_sensor_storagerack2_bottom
      - sensor.ble_temperature_xiaomi_sensor_storagerack2_top

history:
  include:
    entities:
      - binary_sensor.door
      - sensor.processor_temperature
      - sensor.load_15m
      - sensor.memory_use_percent
      - sensor.disk_use_percent
      - sensor.ble_humidity_xiaomi_sensor_countertop1
      - sensor.ble_humidity_xiaomi_sensor_countertop2
      - sensor.ble_humidity_xiaomi_sensor_door
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_bottom
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_mid
      - sensor.ble_humidity_xiaomi_sensor_storagerack1_top
      - sensor.ble_humidity_xiaomi_sensor_storagerack2_bottom
      - sensor.ble_humidity_xiaomi_sensor_storagerack2_top
      - sensor.ble_temperature_xiaomi_sensor_countertop1
      - sensor.ble_temperature_xiaomi_sensor_countertop2
      - sensor.ble_temperature_xiaomi_sensor_door
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_bottom
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_mid
      - sensor.ble_temperature_xiaomi_sensor_storagerack1_top
      - sensor.ble_temperature_xiaomi_sensor_storagerack2_bottom
      - sensor.ble_temperature_xiaomi_sensor_storagerack2_top

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret olivia_chat_id
      - !secret heziwm_chat_id

notify:
  - name: olivia
    platform: telegram
    chat_id: !secret olivia_chat_id
  - name: heziwm
    platform: telegram
    chat_id: !secret heziwm_chat_id

