version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /mnt/hass/kl43:/config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    restart: always 
    network_mode: host
    privileged: true
