title: KL43  hass

views:
  - title: Climate
    icon: mdi:cloud
    cards:
      - type: entities
        title: HASS
        entities:
          - sensor.current_version
          - sensor.hacs
          - sensor.connected_clients
      - type: entities
        title: Binary sensors
        entities:
          - binary_sensor.ble_opening_xiaomi_sensor_door_status
          - alert.kl43_door
      - type: entities
        title: PI Sensors
        entities:
          - sensor.processor_temperature
          - sensor.load_15m
          - sensor.memory_use_percent
          - sensor.disk_use_percent
          - alert.pi_health
      - type: entities
        title: Automations
        entities:
          - automation.daily_report_with_unavailable_entities
          - automation.daily_report_with_unknown_state_entities
      - type: entities
        title: Lights
        entities:
          - light.yeelight_ct_bulb_0x0000000007e8ebd6
          - light.yeelight_stripe_0x0000000005000bcd
      - type: entities
        title: Automations
        entities:
          - automation.lights_on
          - automation.lights_off
      - type: history-graph
        title: Humidity
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - sensor.ble_humidity_xiaomi_sensor_countertop1
          - sensor.ble_humidity_xiaomi_sensor_countertop2
          - sensor.ble_humidity_xiaomi_sensor_door
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_bottom
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_mid
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_top
          - sensor.ble_humidity_xiaomi_sensor_storagerack2_bottom
          - sensor.ble_humidity_xiaomi_sensor_storagerack2_top
      - type: history-graph
        title: Temperature
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - sensor.ble_temperature_xiaomi_sensor_countertop1
          - sensor.ble_temperature_xiaomi_sensor_countertop2
          - sensor.ble_temperature_xiaomi_sensor_door
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_bottom
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_mid
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_top
          - sensor.ble_temperature_xiaomi_sensor_storagerack2_bottom
          - sensor.ble_temperature_xiaomi_sensor_storagerack2_top
