title: KL43  hass

views:
  - title: Climate
    icon: mdi:cloud
    cards:
      - type: entities
        title: HASS
        entities:
          - sensor.current_version
          - sensor.hacs
          - sensor.connected_clients
          - alert.kl43_door
      - type: entities
        title: Binary sensors
        entities:
          - binary_sensor.door
      - type: history-graph
        title: PIR history
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - binary_sensor.door
      - type: entities
        title: PI Sensors
        entities:
          - sensor.glances_cpu_thermal_1_temp
          - sensor.glances_cpu_load
          - sensor.glances_ram_used_percent
          - sensor.glances_used_percent
          - sensor.glances_var_lib_docker_used_percent
          - sensor.glances_mnt_hass_used_percent
      - type: entities
        title: Automations
        entities:
          - automation.daily_report_with_unavailable_entities
      - type: history-graph
        title: Humidity
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - sensor.ble_humidity_xiaomi_sensor_countertop1
          - sensor.ble_humidity_xiaomi_sensor_countertop2
          - sensor.ble_humidity_xiaomi_sensor_door
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_bottom
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_mid
          - sensor.ble_humidity_xiaomi_sensor_storagerack1_top
          - sensor.ble_humidity_xiaomi_sensor_storagerack2_bottom
          - sensor.ble_humidity_xiaomi_sensor_storagerack2_top
      - type: history-graph
        title: Temperature
        hours_to_show: 24
        refresh_interval: 5
        entities:
          - sensor.ble_temperature_xiaomi_sensor_countertop1
          - sensor.ble_temperature_xiaomi_sensor_countertop2
          - sensor.ble_temperature_xiaomi_sensor_door
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_bottom
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_mid
          - sensor.ble_temperature_xiaomi_sensor_storagerack1_top
          - sensor.ble_temperature_xiaomi_sensor_storagerack2_bottom
          - sensor.ble_temperature_xiaomi_sensor_storagerack2_top
